### ISSUE TITLE
Null pointer exception in ExchangeSourceImpl.java

### ISSUE THREAD

**Issue by tokarlss** [gdenning/exchange-sync#18]
In the convertToPersonDto method when routing type is compared to "SMTP" there is occasionally a Null pointer exception when the email is an X.400 adress. 

At least in my exchange environment the routing type is NULL in the case of a X.400 email. This causes "email.getRoutingType().equals("SMTP")"  to generate a null pointer exception since there are no .equals on a NULL string.

I changed the line 187 from:
		if (email.getRoutingType().equals("SMTP")) {
to:
		if (email.getRoutingType()!=null && email.getRoutingType().equals("SMTP")) {

This solved the problem for me, if you dont see any side effects from this, please include the change in your code.

**Comment by gdenning** [comment]
Thanks @tokarlss!  I've pushed a fix for the issue, similar to the change you suggested.
