### ISSUE TITLE
Feature request: non-zero return code on server error

### ISSUE THREAD

**Issue by bartlibert** [gdenning/exchange-sync#19]
First of all: thanks for this great tool.
Now, on to my feature request:
I'm using exchange-sync in a crontab. but I'd like to use the "chronic" tool (http://joeyh.name/code/moreutils/). This tool will hide any stderr output, unless the return code is non-zero.
Unfortunately, exchange-sync always has a zero exit code, even if there is a server error. 
It would be nice if an error code was generated if a server error occurs. That way, I would only see error logs in case there is an issue, but nothing when syncing is fine.

**Comment by gdenning** [comment]
Great suggestion. Modified the code to return exit code 1 if an error occurs. I'll create a new release as soon as I have a chance.

**Comment by bartlibert** [comment]
What a quick response, great work!
