### ISSUE TITLE
Problem with whole day appointments

### ISSUE THREAD

**Issue by MatthiasLohr** [gdenning/exchange-sync#21]
Hey,

first of all: Thank you very much for this tool! I love it! But maybe i found a little bug:

I'm using your tool for syncing Exchange to Google Calendar, without RTM. Syncing "default" appointments works like a charm, but whole day appointments are one day too early in my Google Calendar. For e.g.: The real appointment is on thursday, but Google shows it on Wednesday.

Best regards
Matthias

**Comment by gdenning** [comment]
Hi Matthias!  I've seen that bug before - seems to be some sort of bug in Microsoft's ews-java-api library. I actually thought that they fixed this in the latest version, so I removed the code that compensated for it. I'll look into that more closely; all day appointments seem to be working okay for me, but maybe there's still an edge case. What time zone are you in?

**Comment by MatthiasLohr** [comment]
I'm/my client/my Google Calendar is in Europe/Berlin, but our Exchange Server is a international, organizational Exchange, there i don't know the actual settings.

If you need any help to figure out this bug, let me know.

**Comment by MatthiasLohr** [comment]
Anything new about this?

**Comment by gdenning** [comment]
Hi Matthias, I think I found the bug and I've implemented a fix. Looks like I made a silly mistake when attempting to truncate the time off all day appointments, which is no longer necessary after some recent Microsoft fixes to the EWS library. Please try out the latest (1.0.5) release and let me know if that fixes the issue for you.

**Comment by MatthiasLohr** [comment]
Not completeley. The most items are now on their right place, but one exception:

I have a serial appointment (every thursday, the whole day, MEST). For next week, i moved a single element of these series to wednesday. This element is now shown in the GMT timezone, so it covers tuesday and wednesday in my calender:
![image](https://cloud.githubusercontent.com/assets/781926/26092129/84e30c04-3a0f-11e7-8302-50f76fafc519.png)

Additionally (same entry), the "whole day" flag at Google Calendar is not set, instead the appointment is configured with 24 hours duration:

![image](https://cloud.githubusercontent.com/assets/781926/26092095/55c0ecca-3a0f-11e7-9096-5e371f700030.png)

**Comment by gdenning** [comment]
Thanks so much for the PR Matthias!  I've merged it into master.

**Comment by MatthiasLohr** [comment]
How about a fresh release including the fix?
