### ISSUE TITLE
Need some way of disabling email notifications to meeting attendees

### ISSUE THREAD

**Issue by lewisd32** [gdenning/exchange-sync#9]
Whenever I change the reminders, or delete an exchange-synced event from my google calendar, it's emailing everyone.  I really don't want it to do that.  Maybe a flag to tell it to somehow modify the calendar events it sets up in google, so that all the email addresses are changed, or just moved to the notes, or something.

**Comment by gdenning** [comment]
I've fixed this by adding an option to the exchangesync.properties file called "obfuscateAttendeeEmails".  If you set it to "obfuscateAttendeeEmails=true", then the email addresses of all attendees is obfuscated so Google can't email the attendees.  It's definitely a hack, but it resolves the issue.
